import os
import asyncio
import subprocess
import tempfile
import json
from typing import Optional, Dict, Any
import logging

logger = logging.getLogger(__name__)

class SlicerService:
    def __init__(self):
        # Common OrcaSlicer installation paths on macOS
        self.slicer_paths = [
            "/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer",
            "/Applications/OrcaSlicer.app/Contents/Resources/OrcaSlicer",
            "/usr/local/bin/orcaslicer"
        ]
        self.slicer_cmd = self._find_slicer()

    def _find_slicer(self) -> Optional[str]:
        """Find OrcaSlicer executable"""
        for path in self.slicer_paths:
            if os.path.exists(path):
                logger.info(f"Found OrcaSlicer at: {path}")
                return path

        # Try to find in PATH
        try:
            result = subprocess.run(["which", "orcaslicer"], capture_output=True, text=True)
            if result.returncode == 0:
                path = result.stdout.strip()
                logger.info(f"Found OrcaSlicer in PATH: {path}")
                return path
        except Exception:
            pass

        logger.warning("OrcaSlicer not found. Falling back to basic G-code generation.")
        return None

    async def slice_to_gcode(self,
                           stl_path: str,
                           filename: str = "model",
                           layer_height: float = 0.2,
                           infill: float = 15.0) -> Dict[str, Any]:
        """
        Slice STL file to G-code using OrcaSlicer
        """
        output_dir = os.path.dirname(stl_path)
        gcode_path = os.path.join(output_dir, f"{filename}.3mf")

        if not self.slicer_cmd:
            # Generate basic G-code for testing when OrcaSlicer is not available
            return await self._generate_basic_gcode(stl_path, gcode_path)

        try:
            logger.info(f"Slicing {stl_path} with layer height {layer_height}mm, {infill}% infill")

            # Create OrcaSlicer configuration
            config = self._create_bambu_config(layer_height, infill)
            config_path = os.path.join(output_dir, "bambu_config.ini")

            with open(config_path, 'w') as f:
                f.write(config)

            # Run OrcaSlicer CLI
            cmd = [
                self.slicer_cmd,
                "--load", config_path,
                "--output", gcode_path,
                stl_path
            ]

            process = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )

            stdout, stderr = await process.communicate()

            if process.returncode != 0:
                error_msg = stderr.decode() if stderr else "Unknown OrcaSlicer error"
                logger.error(f"OrcaSlicer failed: {error_msg}")
                # Fall back to basic G-code generation
                return await self._generate_basic_gcode(stl_path, gcode_path)

            if not os.path.exists(gcode_path):
                logger.warning("3MF file was not created, falling back to basic G-code")
                return await self._generate_basic_gcode(stl_path, gcode_path)

            # Parse print time and filament usage from OrcaSlicer output
            stats = self._parse_slicer_output(stdout.decode())

            logger.info(f"Successfully sliced to: {gcode_path}")
            return {
                "gcode_path": gcode_path,
                "print_time": stats.get("print_time"),
                "filament_used": stats.get("filament_used")
            }

        except Exception as e:
            logger.error(f"Error during slicing: {str(e)}")
            # Fall back to basic G-code generation
            return await self._generate_basic_gcode(stl_path, gcode_path)

    def _create_bambu_config(self, layer_height: float, infill: float) -> str:
        """
        Create OrcaSlicer configuration for Bambu A1 mini
        """
        return f"""
# Bambu A1 mini configuration
printer_model = Bambu A1 mini
layer_height = {layer_height}
first_layer_height = 0.2
fill_density = {infill}%
print_speed = 60
travel_speed = 120
first_layer_speed = 30
nozzle_diameter = 0.4
filament_diameter = 1.75
bed_temperature = 60
nozzle_temperature = 220
retraction_distance = 0.8
support_material = 1
support_material_threshold = 45
brim_width = 3
"""

    async def _generate_basic_gcode(self, stl_path: str, gcode_path: str) -> Dict[str, Any]:
        """
        Generate basic G-code template when OrcaSlicer is not available
        """
        basic_gcode = """
; Basic G-code for Bambu A1 mini - Generated by BambuAgent
; This is a placeholder - real slicing should be done with OrcaSlicer

; Printer: Bambu A1 mini
; Filament: PLA
; Layer Height: 0.2mm

; Start G-code
M104 S220 ; Set nozzle temperature
M140 S60  ; Set bed temperature
G28       ; Home all axes
G1 Z15.0 F9000 ; Move Z up
M109 S220 ; Wait for nozzle temperature
M190 S60  ; Wait for bed temperature

; Print moves would go here
; (This is just a test file)

G1 X100 Y100 Z0.2 F3000
G1 E10 F300

; End G-code
M104 S0   ; Turn off nozzle
M140 S0   ; Turn off bed
G28 X0    ; Home X
M84       ; Disable steppers
"""

        # Write basic G-code to file
        with open(gcode_path, 'w') as f:
            f.write(basic_gcode)

        return {
            "gcode_path": gcode_path,
            "print_time": "Estimated 30 minutes",
            "filament_used": "Estimated 5g"
        }

    def _parse_slicer_output(self, output: str) -> Dict[str, Any]:
        """
        Parse OrcaSlicer output for print statistics
        """
        stats = {}

        lines = output.split('\n')
        for line in lines:
            line = line.strip().lower()

            if 'print time' in line or 'estimated time' in line:
                stats['print_time'] = line.split(':')[-1].strip()

            elif 'filament used' in line or 'material usage' in line:
                stats['filament_used'] = line.split(':')[-1].strip()

        return stats

    def get_slicer_info(self) -> dict:
        """
        Get OrcaSlicer version and installation info
        """
        if not self.slicer_cmd:
            return {"installed": False, "path": None, "version": None}

        try:
            result = subprocess.run([self.slicer_cmd, "--version"],
                                  capture_output=True, text=True)
            version = result.stdout.strip() if result.returncode == 0 else "Unknown"

            return {
                "installed": True,
                "path": self.slicer_cmd,
                "version": version
            }
        except Exception as e:
            return {
                "installed": False,
                "path": self.slicer_cmd,
                "version": None,
                "error": str(e)
            }